name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master  # Ajusta esto a tu rama por defecto
  pull_request:
    branches:
      - master  # Ajusta esto a tu rama por defecto

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # Asegúrate de que esta versión coincide con la que utilizas localmente

    # Resto de tus pasos...
